### ISSUE TITLE
User-signout validation issue

### ISSUE THREAD

**Issue by santhosh156** [santhosh156/Quora-clone#2]
Requirement:
If the access token provided by the user is valid, update the LogoutAt time of the user in the database and return the 'uuid' of the signed out user from 'users' table and message 'SIGNED OUT SUCCESSFULLY' in the JSON response with the corresponding HTTP status.

Scenario:
For both valid inputs and invalid inputs the response is the same as shown below:
message code -'SGR-001' and message - 'User is not Signed in'.

Also, the logout_at column in user_auth is not getting updated for valid use cases.

**Comment by anirudhpundhir** [comment]
bearer token was creating problem issue resolved

**Comment by Maitrysu** [comment]
thanx Anirudh
